LOAD DATA LOCAL INFILE "../data/reg_info.dat" INTO TABLE Registration FIELDS TERMINATED BY ",";
LOAD DATA LOCAL INFILE "../data/supply.dat" INTO TABLE Supply FIELDS TERMINATED BY ",";
LOAD DATA LOCAL INFILE "../data/demand.dat" INTO TABLE Demand FIELDS TERMINATED BY ",";
LOAD DATA LOCAL INFILE "../data/order.dat" INTO TABLE Order_History FIELDS TERMINATED BY ",";